ALTER TABLE `user`
    ADD COLUMN `USER_GOOGLE_ID` VARCHAR(255) NULL;

CREATE UNIQUE INDEX `UK_USER_GOOGLE_ID`
    ON `user` (`USER_GOOGLE_ID`);

ALTER TABLE `user`
    ADD COLUMN `USER_GOAL_WEIGHT` DOUBLE NULL,
    ADD COLUMN `USER_GOAL_DATE` DATE NULL;
